### ISSUE TITLE
Obfuscation failed for code with `super`

### ISSUE THREAD

**Issue by tri170391** [javascript-obfuscator/javascript-obfuscator#110]
Can be reproduced on online demo:
```
class BaseClass {
    constructor(foo) {
        this._foo = foo;
    }
  
      get foo() {
        return this._foo;
    }
}

class BarClass extends BaseClass {
    constructor(foo, bar) {
        super(foo);
         this._bar = bar;
    }
  
      get bar() {
        return this._bar;
    }
}

const a = new BarClass('foo', 'bar');
console.log(a.foo);
console.log(a.bar);
```

Attempt to obfuscate this code snippet with everything off and `Mangle Variable Names` on returns: `Error: Unknown node type Super.`

**Comment by sanex3339** [comment]
`Mangle` option is using `esmangle` library that may not support some `es6` constructions.

**Comment by tri170391** [comment]
In this case it is ES6 inheritance that it is not supporting, which is quite a major issue IHMO.

**Comment by sanex3339** [comment]
In the future i'll remove `esmangle` on my own transformer.

**Comment by sanex3339** [comment]
Right now you can disable mangle option and use `uglify-es` over obfuscated code.

**Comment by aurelhann** [comment]
Same as @tri170391 i'm waiting the future release for this bug.
It will be a complete and nice obfuscator after that. ;)

**Comment by sanex3339** [comment]
Right now it's hard to fully recreate `mangle` functional from `esmangle`, `uglifyjs` or similar packages. 

This packages can reset mangled names for block scopes in which this names are not affected by parent block scopes.

For example code:

```
function test () {
    var foo = 1;
    var bar = 2;
    
    function test1 (baz, bark) {

    }
}
```

Will become:
```
function test () {
    var a = 1;
    var b = 2;
    
    function c (a, b) {

    }
}
```

In the example above, parameters `baz` and `bark` will be renamed to `a` and `b`, because `a` and `b` in the parent block scope doesn't affect current block scope.

This is slightly hard to implement with current obfuscator architecture, but right now i can just not reset names for different scopes and each mangled variable name will based on previous mangled name. 

For obfuscated angular 2, this approach gives me mangled names with maxium length of 3 character. So, this is better, than nothing.

**Comment by sanex3339** [comment]
WIP PR here: https://github.com/javascript-obfuscator/javascript-obfuscator/pull/133/files

Currently no ETA

**Comment by malafaya** [comment]
Not sure I undestand the issue but I'm also having trouble (again) with super.
I have "mangle: false" and using v0.12.3.

SyntaxError: 'super' keyword unexpected here
    at createScript (vm.js:74:10)

Relevant obfuscated code

```
(_0x3e1a14=>{
  var _0x1d9054={'QDzag':_0x8b00('0xe3')};
  if(_0x1d9054[_0x8b00('0xe4')]!==_0x8b00('0xe3')) {
      super();
      this[_0x8b00('0xe')]=new _0x209e8b();
....
```

I seems to be using super() outside a class definition.
Could it be the deadCodeInjection (again)?
Although I use super() only once, I find it twice in the obfuscated code, and one of them (not the one above) seems to be inserted correctly inside a class definition.

**Comment by sanex3339** [comment]
> Could it be the deadCodeInjection (again)?

Looks like (

**Comment by sanex3339** [comment]
@malafaya check this issue 
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/136

**Comment by sanex3339** [comment]
If you need new internal mangler right now, you can temporarily install it from master branch of this repository.

**Comment by sanex3339** [comment]
In the upcoming `0.13.0` release `mangle` option will removed and instead of it new `identifierNamesGenerator` option will added.

`identifierNamesGenerator` option right now has two possible values:
* `hexadecimal` (default)
* `mangled`

https://github.com/javascript-obfuscator/javascript-obfuscator/pull/143

**Comment by sanex3339** [comment]
`0.13.0` just released. Have a nice day!
