### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by Luperi** [javascript-obfuscator/javascript-obfuscator#15]
What about adding a new CLI option "sourceMapBaseUrl" that can be used in this way?

`javascript-obfuscator library.js --output library.min.js --sourceMap true --sourceMapBaseUrl "http://localhost/private-folder/"`

I've tested this functionality, wherewith you can upload on server only obfuscated code, and keep locally the map file. So, everybody will see only obfuscated code and those who have the map file locally, will be able to debug the code and see it clearly.

**Comment by Luperi** [comment]
I mean the result will be something like:

```
var _0x2459= ...
//# sourceMappingURL=http://localhost/private-folder/library.min.js.map
```

**Comment by sanex3339** [comment]
Ok, when i will have time i will do it. Will be in 0.8.0.

**Comment by sanex3339** [comment]
I need in some clarification for Node API. 
With CLI usage everything is very clear - name for output source map is based on input source file name or `--output` option value. CLI result consists of one or two files: obfuscated code and source map. 
But for Node API things are slightly different. As output data we getting obfuscated code and source map as `string`. For obfuscated code we don't need to know the name of the output source map. Import of source map is inserted in the obfuscated code only as Base64 encoded `string`, not as url to this source map.

But this logic may cause a misunderstanding because `sourceMapBaseUrl` option will have sense only with CLI usage.

So i can make one more option: `sourceMapName` which will take care about output source map name.
Name can be as raw name `output-source-map-name` or as full source map name `output-source-map-name.map.js`. This value will override source map name which based on input source code name or on output obfuscated code file name.

With Node API usage with this option in obfuscated code wil be inserted source map import, but user should manually (with Node) create a file with source map content (`.getSourceMap()`). And that file should has a path same as source map import path in obfuscated code.

Finally if `sourceMapBaseUrl` is set it will combined with `sourceMapName`.

Your opinion?

**Comment by Luperi** [comment]
For me, yours is a great solution.

**Comment by sanex3339** [comment]
WIP realisation in:
https://github.com/sanex3339/javascript-obfuscator/commit/2dd6f91b7ff03e9acfec67727ee0186b8b541f77
https://github.com/sanex3339/javascript-obfuscator/commit/bc1d4ef609ce0f35623f30716fd0352aba0347de
https://github.com/sanex3339/javascript-obfuscator/commit/42381552e16ace525af64d49409d46281eefff48
https://github.com/sanex3339/javascript-obfuscator/commit/1eeaf7df2b9daeac5e29fb5dcd8352bdf1e8cf72
https://github.com/sanex3339/javascript-obfuscator/commit/5069ec213be2992ef3d3c14b97e5848ba1fe5f9b

**Comment by Luperi** [comment]
Will be in 0.8.0 ?

**Comment by sanex3339** [comment]
Yes. But if you want it, i can release 0.8.0-dev.1 in 4-5 days.

**Comment by Luperi** [comment]
Don't worry, I prefer use a stable version for my production code.

**Comment by sanex3339** [comment]
ready in dev release 
`npm i javascript-obfuscator@beta`

**Comment by sanex3339** [comment]
Right now in dev release here a bug which pass throug options validator base url value without protocol.

This bug is relative to https://github.com/pleerock/class-validator/issues/49

**Comment by sanex3339** [comment]
0.8.0 is ready

**Comment by sanex3339** [comment]
If domain will be incorrect - at first here will be an error (variable `data` undefined) If person, who looking at obfuscated code, will fix error - then infinity loop.
