### ISSUE TITLE
Unable to pass in an existing source map?

### ISSUE THREAD

**Issue by QuantumRevenger** [javascript-obfuscator/javascript-obfuscator#19]
Hi again,

Firstly thanks for fixing the CLI since my initial issue / and the last few updates since.

Secondly, I noticed it is not possible to pass in an existing source map? I have a map from a previous step and would like to ensure this is remapped, just like JSUglify offers.

Would this be possible to add in an update?

**Comment by sanex3339** [comment]
I doing it in the webpack plugin, so i can move it from plugin to obfuscator

**Comment by sanex3339** [comment]
But i still not shure what i should do this - it is really important to make this functional? Because you can remap exiting source map with source map from obfuscator with help of https://github.com/azu/multi-stage-sourcemap

https://github.com/javascript-obfuscator/webpack-obfuscator/blob/master/index.ts#L72

**Comment by sanex3339** [comment]
closed. for this functional use https://github.com/azu/multi-stage-sourcemap
