### ISSUE TITLE
duplicate global variables in multiple files for StringArray option

### ISSUE THREAD

**Issue by akaJes** [javascript-obfuscator/javascript-obfuscator#193]
used `gulp-javascript-obfuscator` plugin
parameter `seed` used default (0)
after obfuscation some files has the same name of global variable of strings array
how to prevent this behavior of StringArray option?

**Comment by akaJes** [comment]
gulp-javascript-obfuscator@1.1.4
javascript-obfuscator@0.13.0

**Comment by sanex3339** [comment]
You using `identifierNamesGenerator: 'mangled'?

**Comment by akaJes** [comment]
no - default hex

**Comment by sanex3339** [comment]
Firstly i don't know how exactly `gulp-javascript-obfuscator` working.

In theory it possible, because of random generator can proceed same values in a short range.
You can try 0.14.1 version where i added `identifiersPrefix` option and recursive directory obfuscation via CLI. During recursive directory obfuscation all identifiers inside each file will prefixed with their own prefix.

**Comment by akaJes** [comment]
`gulp-javascript-obfuscator` plugin calls javascript-obfuscator for each file simply with the same parameters

new options - it is good!!

maybe simpler use https://nodejs.org/api/crypto.html or https://developer.mozilla.org/ru/docs/Web/API/RandomSource/getRandomValues instead oldschool Math.Random?

**Comment by sanex3339** [comment]
I'm using `chance`
https://www.npmjs.com/package/chance

**Comment by sanex3339** [comment]
Closed. Use `identifiersPrefix` option
