### ISSUE TITLE
how to De-obfuscat from the obfuscated code?

### ISSUE THREAD

**Issue by juniorfans** [javascript-obfuscator/javascript-obfuscator#352]
i wonder if there any way to get source code from the obfuscated code?

**Comment by Extarys** [comment]
You could try, there are some tools out there but be prepared, it may take a long time.

We could close this as it is a question that could be better answer on SO and wasn't updated in a long time.

**Comment by jesper-sjovall** [comment]
We did a quick review of the tool and put 4 hours on decode the output, and the result is you can quite easy way recreate a project to a working state (not perfect created but understandable code)

But still I will say this is one of the better tool for Javascript I have seen.

**Comment by Extarys** [comment]
Thanks @jesper-sjovall for this. I was also curious about how effective this tool was. Do you have any suggestions for the collaborator on how they could make this obfuscator harder to deobfuscate? :P

**Comment by jesper-sjovall** [comment]
Hi.

Very good question base concept I use was

> require('./testclass-obfuscated.js').toString()'function () { console.log("hello"); }'

That returning source code the given function or class.
After that I use the internal function from the obfuscator code together
with regexp for cleanup the code even more.
The output after this two step are something that are close to the source
code except for all variable are still obfuscate, this can't be undo
due to missing information but by preforming a variable replacement  you
can at lest make the code more easy understanding.


/ Jesper.




_______________________________________________

* Jesper Sjövall*
 Developer

 Skype: jesper.sjovall
 jesper.sjovall@appland.se
 (PGP Public Key 0xE3CE2E47F69358CC)
<http://keyserver.pgp.com/vkd/Captcha.event?&&SearchCriteria=jesper.sjovall%40appland.se>
<jesper.sjovall@appland.se>

 *Appland AB*
 Sweden
 www.applandinc.com | linkedin.com/company/appland-ab
_______________________________________________



Den fre 1 mars 2019 kl 21:50 skrev Jeremy <notifications@github.com>:

**Comment by Extarys** [comment]
Oh that's clever.

If you ever have any idea to improve this, many people would be happy with 1 more contributor :beers:

**Comment by jesper-sjovall** [comment]
Hi

Please have a look on a more extended example at
https://docs.appland.se/javascript-obfuscator-example.zip
( Can't send this as attach in the email due to Google blocking Javascript
files)

The result are not perfect but depending on you programming pattern I will
say the system give away for much info.
One ide to improving the code and also optimize code is the code are only
decoded first time it is used and
not when the code is first created.

/ Jesper.



_______________________________________________

* Jesper Sjövall*
 Developer

 Skype: jesper.sjovall
 jesper.sjovall@appland.se
 (PGP Public Key 0xE3CE2E47F69358CC)
<http://keyserver.pgp.com/vkd/Captcha.event?&&SearchCriteria=jesper.sjovall%40appland.se>
<jesper.sjovall@appland.se>

 *Appland AB*
 Sweden
 www.applandinc.com | linkedin.com/company/appland-ab
_______________________________________________



Den mån 4 mars 2019 kl 22:56 skrev Jeremy <notifications@github.com>:

**Comment by Extarys** [comment]
So we should either decode the code when we need it or make it somehow polymorphic?

I think JScrambler obfuscation is polymorphic. It would be terrific but I guess it would be pretty hard to implement.

**Comment by Extarys** [comment]
@sanex3339 how much time and energy would this require? I'm very curious.
