### ISSUE TITLE
disableConsoleOutput question

### ISSUE THREAD

**Issue by RogerHardiman** [javascript-obfuscator/javascript-obfuscator#40]
Hi
Can I ask how disableConsoleOutput works please?
I have a node project that has two files
File 1 - the main application. It handles a 'log' event and writes logs to the console.
    my_class.on('log', function(msg) {console.log(msg)});

File 2 - My javascript class which uses Node's Event Emit to fire a 'log' event to the main application.
(the main application is the only place where there is a console.log() call.

I am only obfuscating File 2.
But if I onfuscate it, the main application (File1) does not write to the console.
So I have to remember to use the --disableConsoleOutput even though the javascript I am obfuscating does not write to the console.

Is this designed to be this way?

**Comment by sanex3339** [comment]
`disableConsoleOutput` option adds small additional piece of code that after execution sets all `window.console.xxx` function to `null` value.

So, after this piece of code will execute, you wont see anything in the console.

This option is `true` by default, because most JS apps usually don't have console output on production.

**Comment by RogerHardiman** [comment]
Thanks for explaining the way it works.
