### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by mariolatiffathy** [javascript-obfuscator/javascript-obfuscator#571]
Hi,

I am interested in your project and I have some questions regarding it.

- Does it being open source help people to deobfuscate it?
- How easy is it to deobfuscate Javascript Obfuscator?
- Can de4js deobfuscate this?
- Can I use Javascript obfuscator using PHP? (I am planning to obfuscate a dynamic JS code using PHP if possible)

Kind regards.

**Comment by sanex3339** [comment]
1) I think, that no, but this is question for someone who did it
2) This is question for someone who did it
3) I don't know 
4) no, this is javascript library

**Comment by kittenswolf** [comment]
I can partly answer question 2 - the string array obfuscation can easily be deobfuscated by hooking up a webdriver to the target javascript file and evaluating all the string functions.

**Comment by sanex3339** [comment]
`stringArray` itself can be reverted by automatization (simple AST deobfuscator), BUT with the combination of `stringArrayEncoding`, `shuffleStringArray`, `rotateStringArray`, and `controlFlowFlattening` this is the more hard mechanism.

Especially `controlFlowFlattening`, because at first, this transformation moves string from its original location into the function through few other function calls (depends on the level of the deep of the function, where this string was placed). And even if someone moves strings to its original places, reverting of the `controlFlowFlattening` transformations is a really hard task.

What about additional code helpers, like `selfDefending` and others?
I added them, but currently, I think that this is not the best part of the obfuscation, because these helpers can be detected and removed.

The primary focus of the next versions of the obfuscator - additional code transformations, because this is the most stable mechanism to protect original code.

**Comment by sanex3339** [comment]
Closed, because of no response
