### ISSUE TITLE
javascript-obfuscator breaks YML parsing

### ISSUE THREAD

**Issue by thisismydesign** [javascript-obfuscator/javascript-obfuscator#790]
See: https://github.com/electron-userland/electron-builder/issues/5234 and https://github.com/electron-userland/electron-builder/issues/5366

## Your Environment

* Obfuscator version used: 2.6.1
* Node version used: v12.13.0

These kinds of issues are crazy hard to debug from a dev perspective.  Wanted to raise this issue here because I couldn't find it raised yet. Hopefully this is useful but I can't offer more support as I'm no longer using this project.

**Comment by sanex3339** [comment]
Repo with the bug
https://github.com/rasgo-cc/electron-updater-obfuscated

**Comment by sanex3339** [comment]
@rasgo-cc so, current repo without the bug?

**Comment by sanex3339** [comment]
Cannot reproduce, as you said. Waiting for the example with the actual bug.
Also, try with the new `2.6.4` version, I fixed the bug with `transformObjectKeys` but seems you got this bug without this option.

**Comment by sanex3339** [comment]
@rasgo-cc any new info?

**Comment by rasgo-cc** [comment]
@sanex3339 sorry probably won't able to be back at this until the end of the year.

I was expecting the repo above to reproduce the error but as it doesn't it's probably related with something else I have in my `node_modules` that somehow ends up biting the YAML parsing. 

Just for reference: I started using the webpack loader (instead of plugin) to obfuscate only my code instead of the whole bundle and this way I don't get this error.  As far as I can remember obfuscating the whole bundle had other (apparently) smaller issues: Mixpanel lib was not working properly (some network error).

**Comment by sanex3339** [comment]
Ok. Create a new issue when you now how to reproduce this error.

**Comment by AlexxxRu** [comment]
@sanex3339 @rasgo-cc 
I've faced the same issue with the js-yaml `load`. Setting `simplify: false` to obfuscator config solved it.
I'll try to prepare a reproducible build during the next few weeks.

**Comment by sanex3339** [comment]
It would be nice
