### ISSUE TITLE
debugProtection is easy to bypass even if selfDefending is enabled

### ISSUE THREAD

**Issue by Andgoncharov** [javascript-obfuscator/javascript-obfuscator#95]
I've tried out javascript-obfuscator and it seems very interesting to me. You're making a really good project!

Can you please clarify the following? I've chosen medium (optimal) configuration, which is described in the readme file and enabled debugProtection with debugProtectionInterval plus added domainLock. Then I've obfuscated my code and checked whether I can bypass protection.

debugProtection was easy to bypass. I've just searched for base64 representation of "debugger" string and replaced it with base64 "console.log(0)" string. After that change my code worked perfectly in browser and I was able to use Dev tools. I expected that such change shouldn't work because of selfDefending. Did I miss something in the configuration or that's a weak point?

**Comment by sanex3339** [comment]
Hi! Currently self defending not affected debug protection. But i'll fix it!

**Comment by Andgoncharov** [comment]
Perfect! Thanks!

**Comment by fedyd** [comment]
Hi,

I have tried the online version of javascript-obfuscator at https://javascript-obfuscator.org/.
I think to have the same issue as Andgoncharov. I decided to insert the debug protection also with the interval protection in my code. I obfuscated it and loaded on my website. I tried to open the dev tools of Mozilla Firefox and could read the plain text (also formatted) of my javascript code (without doing any bypass). I am not very skilled so I don't know if I have missed something, but that I wrote is what I did.
Federico

**Comment by sanex3339** [comment]
Hi. Debug protection adding `debugger` calls in loop, so when you will open dev tools - debugger will calledd on one part of code every time without continue of execution. This prevent from debugging of the code with break points and console logs, but you still will see obfuscated code.

Right now you can remove debugger calls from the code because self defending not affected this calls but i working on it.

Debug protection - additional step to defend the code, main and most powerful options to defend your code -

stringArray, stringArrayEncoding, controlFlowFlattening and deadCodeInjection 

This options eill ttansform your code into fornat that very hard to read.

PS: https://javascript-obfuscator.org/ not official site, i dont know who made it and looks like it contains old version of obfuscator. Official UI https://javascriptobfuscator.herokuapp.com

**Comment by fedyd** [comment]
Hi Timofey,

thank you very much for your answer. I appreciated it. I will try to
obfuscate my code using the official website and
following your advices and will let you know how it works (I think I will
try tomorrow).
Thank you very much again and kind regards,

Federico

2017-09-20 11:36 GMT+02:00 Timofey Kachalov <notifications@github.com>:

**Comment by sanex3339** [comment]
Closed as old

**Comment by hktalent** [comment]
@sanex3339 
Suggest that debugProtection support both the current bool and a function as a parameter, so that we can easily call our own defined methods. That is to say, when trying to crack or debug code, I want to call my own functions, such as hiding the body
